main: "dev.aporofobia.order.OrderedPlugin"
version: "1.0.1"
name: "5star-sharpenItemsAfterDeath"
description: "Sharpen Items After Death plugin written by aporofobia"
author: "aporofobia"
api-version: "1.13"